import React from 'react';
import { useAgrizen } from '../../context/AgrizenContext';
import { MOCK_REPORTS } from '../../data/mockData';
import {
  FileText,
  Download,
  Calendar,
  Building2,
  FileSpreadsheet,
  Printer,
  ChevronLeft
} from 'lucide-react';

export function AdminReports() {
  const { addToast, playChime } = useAgrizen();

  const handleDownload = (report) => {
    playChime();
    addToast(`Downloaded ${report.title} (${report.size})`, "success");
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
      <div>
        <h2 style={{ fontSize: '1.35rem', color: 'var(--gov-slate-900)' }}>
          Statutory Reports &amp; Daily Procurement Records (DPR)
        </h2>
        <p style={{ fontSize: '0.82rem', color: 'var(--gov-slate-600)' }}>
          Official state reporting documents, mill dispatch ledgers, and PFMS financial statements
        </p>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
        {MOCK_REPORTS.map(rep => (
          <div key={rep.id} className="report-card">
            <div style={{ display: 'flex', alignItems: 'flex-start', gap: '12px' }}>
              <div style={{
                width: '44px',
                height: '44px',
                borderRadius: 'var(--radius-md)',
                backgroundColor: rep.type === 'PDF' ? '#fee2e2' : '#dcfce7',
                color: rep.type === 'PDF' ? '#b91c1c' : '#15803d',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                flexShrink: 0
              }}>
                <FileText size={22} />
              </div>

              <div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <h4 style={{ fontSize: '1.02rem', color: 'var(--gov-slate-900)' }}>
                    {rep.title}
                  </h4>
                  <span className="gov-badge gov-badge-slate" style={{ fontSize: '0.65rem' }}>
                    {rep.type} • {rep.size}
                  </span>
                </div>

                <div style={{ fontSize: '0.78rem', color: 'var(--gov-slate-500)', marginTop: '2px' }}>
                  Period: <strong>{rep.period}</strong> • Generated by: {rep.generatedBy} • {rep.recordsCount} District Units
                </div>

                <p style={{ fontSize: '0.84rem', color: 'var(--gov-slate-600)', marginTop: '6px', lineHeight: 1.45 }}>
                  {rep.summary}
                </p>
              </div>
            </div>

            <button
              className="gov-btn gov-btn-secondary gov-btn-sm"
              onClick={() => handleDownload(rep)}
              style={{ flexShrink: 0 }}
            >
              <Download size={14} />
              <span>Download Official Copy</span>
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}
